dist: bionic
language: clojure
jdk:
  - openjdk8
  - openjdk10
  - openjdk11
node_js:
  - "8"
script:
  - lein do clean, clj-test
  - lein do clean, javac, cljs-test
cache:
  directories:
  - $HOME/.m2
